const translations = {
  th: {
    "The Insider": "The Insider",
    "Select Player Group:": "เลือกกลุ่มผู้เล่น:",
    "Main": "หลัก",
    "Words": "คำ",
    "Players": "ผู้เล่น",
    "Stats": "สถิติ",
    "Statistics": "สถิติ",
    "Current Game": "เกมปัจจุบัน",
    "Today": "วันนี้",
    "All Time": "ทั้งหมด",
    "Reset Statistics": "รีเซ็ตสถิติ",
    "Reset All Statistics": "รีเซ็ตสถิติทั้งหมด",
    "Last Reset Date": "วันที่รีเซ็ตสถิติล่าสุด",
    "Start New Game": "เริ่มเกมใหม่",
    "View All-Time Scores": "ดูคะแนนทั้งหมด",
    "Word Management": "จัดการคำ",
    "Enter word": "ใส่คำ",
    "Add Word": "เพิ่มคำ",
    "Player Groups": "กลุ่มผู้เล่น",
    "Enter group name": "ใส่ชื่อกลุ่ม",
    "Add Group": "เพิ่มกลุ่ม",
    "Players in": "ผู้เล่นใน",
    "Enter player name": "ใส่ชื่อผู้เล่น",
    "Add Player": "เพิ่มผู้เล่น",
    "All-Time Leaderboard": "ตารางคะแนนทั้งหมด",
    "-- Select a group --": "-- เลือกกลุ่ม --",
    "No active game": "ไม่มีเกมที่กำลังเล่น",
    "Please select a group to view scores": "กรุณาเลือกกลุ่มเพื่อดูคะแนน",
    "No scores yet": "ยังไม่มีคะแนน",
    "Never reset": "ยังไม่เคยรีเซ็ต",
    "Last reset:": "รีเซ็ตล่าสุด:"
  },
  en: {
    "The Insider": "The Insider",
    "Select Player Group:": "Select Player Group:",
    "Main": "Main",
    "Words": "Words",
    "Players": "Players",
    "Stats": "Stats",
    "Statistics": "Statistics",
    "Current Game": "Current Game",
    "Today": "Today",
    "All Time": "All Time",
    "Reset Statistics": "Reset Statistics",
    "Reset All Statistics": "Reset All Statistics",
    "Last Reset Date": "Last Reset Date",
    "Start New Game": "Start New Game",
    "View All-Time Scores": "View All-Time Scores",
    "Word Management": "Word Management",
    "Enter word": "Enter word",
    "Add Word": "Add Word",
    "Player Groups": "Player Groups",
    "Enter group name": "Enter group name",
    "Add Group": "Add Group",
    "Players in": "Players in",
    "Enter player name": "Enter player name",
    "Add Player": "Add Player",
    "All-Time Leaderboard": "All-Time Leaderboard",
    "-- Select a group --": "-- Select a group --",
    "No active game": "No active game",
    "Please select a group to view scores": "Please select a group to view scores",
    "No scores yet": "No scores yet",
    "Never reset": "Never reset",
    "Last reset:": "Last reset:"
  }
};